### ISSUE TITLE
Intution on setting number of gaps

### ISSUE THREAD

**Issue by tyokota** [WenjieZ/TSCV#11]
If for example, I have data without gaps, when and why would I still create a break between my train and validation? I have seen the argument for setting gaps when the period that needs to be predicted may be N days after the train. Are there other reasons? And if so, what is the intuition on knowing how many gaps to include before/after the training set?

**Comment by fengchi863** [comment]
I think it may be for improve model rubust because the fit_data and train_data always have gaps such as valid_data or test_data.
