### ISSUE TITLE
split.py depends on deprecated / newly private method `_safe_indexing` in scikit-learn 0.24.0

### ISSUE THREAD

**Issue by rob-s-626** [WenjieZ/TSCV#12]
Just flagging a minor issue:

We found this after `poetry update`-ing our dependencies, inadvertently bumping scikit-learn to `0.24.0`. This broke code we have that uses `tscv`

relevant scikit-learn source-code from version `0.23.0`
https://github.com/scikit-learn/scikit-learn/blob/0.23.0/sklearn/utils/__init__.py#L274-L275

The method has been made private in scikit-learn `0.24.0`: https://github.com/scikit-learn/scikit-learn/blob/0.24.0/sklearn/utils/__init__.py#L271

I did not investigate further, we pinned `scikit-learn` to `0.23.0` and that's OK for now, but some refactoring may be in order to move off the private method.

**Comment by WenjieZ** [comment]
Thank you for the report. I plan to release a newer version of 'tscv' in March, which will solve this problem as well as aggregate other enhancements. 

If you notice any other issues, welcome to file an report.

**Comment by WenjieZ** [comment]
Will adopt the same solution as https://github.com/DistrictDataLabs/yellowbrick/pull/1138.

**Comment by WenjieZ** [comment]
Hi @rob-s-626 , you can checkout [v0.0.5 pre-release](https://github.com/WenjieZ/TSCV/releases/tag/v0.0.5-rc1) for early testing.
