### ISSUE TITLE
Stratify?

### ISSUE THREAD

**Issue by jmrichardson** [WenjieZ/TSCV#13]
Hi, 

Would you consider adding stratified support to balance the classes (of course keeping order)?

**Comment by jmrichardson** [comment]
Hi, reading issue #12 it appears that you are working on a new version of tscv (looking forward to it).  I did a bit of hackery to get it to work for my particular use case.  I thought I would share the code just in case you were interested in what I was originally looking for (I am sure you could do a much better job):

Essentially, I just created random under_sampler (preserving order) of the majority class in the base class:

```
    def under_sample(self, X, y, indices):
        """Under samples majority class"""
        if len(np.unique(y)) != 2:
            raise ValueError("Must have at 2 classes in y")
        y_fold = y[indices]
        minority = np.argmin(np.bincount(y_fold))
        majority = np.argmax(np.bincount(y_fold))
        if minority != majority:
            sample_size = (y_fold == minority).sum()
            majority_indices = np.random.choice(np.where(y_fold == majority)[0], sample_size, replace=False)
            minority_indices = np.where(y_fold == minority)[0]
            sampled_indices = sorted(np.concatenate([majority_indices, minority_indices]))
            return indices[sampled_indices]
        else:
            return indices
```

Then for Gap classes in the yield, I balance the Train set (not test).  For example, I updated the yield in:

```
    def __complement_indices(self, indices, n_samples, X, y):
        before, after = self.gap_before, self.gap_after
        for index in indices:
            complement = np.arange(n_samples)
            for i in index:
                begin = max(i - before, 0)
                end = min(i + after + 1, n_samples)
                complement = np.setdiff1d(complement, np.arange(begin, end))
            yield self.under_sample(X, y, complement)
```

This was just a quick hack, no user arguments, tests or PR.  Hopefully you will consider this type of functionality in your upcoming release.  Thanks for the great work

**Comment by WenjieZ** [comment]
Sorry for the late reply. After checking up on my budget, I am afraid that this feature will not be available any time soon 😢. I will consider reopening it if there are enough demands.
