### ISSUE TITLE
GapWalkForward Issue with Scikit-learn 0.24.1

### ISSUE THREAD

**Issue by mksamelson** [WenjieZ/TSCV#24]
When I upgrade to Scikit-learn 0.24.1 I get an issue:

`cannot import name 'safe_indexing' from 'sklearn.utils' `

This appears to be a change within scikit-learn as indicated here:

https://stackoverflow.com/questions/65602076/yellowbrick-importerror-cannot-import-name-safe-indexing-from-sklearn-utils

No issue using scikit-learn 0.23.2

**Comment by WenjieZ** [comment]
This issue has recently be solved in the pre-release `v0.0.5-rc1` (I guess you are using `v0.0.4`). You can download the latest release here: https://github.com/WenjieZ/TSCV/releases/tag/v0.0.5-rc1

Check out [this blog post](http://www.zhengwenjie.net/tscvfuture/) for more details.

**Comment by WenjieZ** [comment]
solved
