### ISSUE TITLE
Implement rolling overlapping CV

### ISSUE THREAD

**Issue by takiholadi** [WenjieZ/TSCV#4]
Like this:
```
    |========****    |
    |  ========****  |
    |    ========****|
```
May be params `n_splits` and `test_size` needed.

**Comment by WenjieZ** [comment]
Although I wasn't working on it, I never forgot it. The above PR should meet your need.

The relevant parameter is dubbed `rollback_size`, default to 0. The whole signature is 
```python
GapWalkForward(n_splits=5, max_train_size=None, test_size=None, gap_size=0, rollback_size=0)
```

Moreover, it has the bonus that **you can use _gaps_ with it**.

Visualization:
```
    |=======o****    |
    |  =======o****  |
    |    =======o****|
```
