### ISSUE TITLE
Does this work with sklearn 1.2?

### ISSUE THREAD

**Issue by justinsl** [WenjieZ/TSCV#48]
There seems to be some changes with the sklearn library that's causing some compatibility issues with tscv. Just wondering if im doing something wrong or tscv currently doesn't support sklearn 1.2

**Comment by justinsl** [comment]
Great work btw, tscv has been very helpful

**Comment by WenjieZ** [comment]
Hi @justinsl , thank you for your interest in TSCV.

Have you tried TSCV `v0.1.3`? How did you install TSCV? From pip or conda? The newest version can be installed via pip but not conda yet.

**Comment by justinsl** [comment]
Alright let me try that 😁
I've been installing with conda

**Comment by WenjieZ** [comment]
@justinsl,
Good news! The latest version of tscv was just deployed to the conda-forge channel. It is compatible with scikit-learn v1.2 and the ealier versions. Give it a spin!
