### ISSUE TITLE
Release 0.0.4 for GridSearch compat

### ISSUE THREAD

**Issue by wderose** [WenjieZ/TSCV#6]
Would it be possible to issue a new release on PyPI to include the latest changes from [this commit](https://github.com/WenjieZ/TSCV/commit/fa7347effb4c2f0757f39a3334ce46427fca66a7) which aligns the `get_n_splits` method signature with the abstract method signature required by GridSearchCV?

**Comment by wderose** [comment]
cc: @WenjieZ

**Comment by WenjieZ** [comment]
Uploaded the new version to PyPi. Please let me know whether that solves your problem.
